"""
This file contains constants for use in the other modules (or for independent
use)
"""

ONE_MINUTE = 1
ONE_HOUR_MINUTES = 60
ONE_DAY_MINUTES = 1440

ONE_TIMESTEP = 5  # 5 * ONE_MINUTE
ONE_TIMESTEP_FREQ = "5T"

ONE_HOUR_TIMESTEPS = 12  # ONE_HOUR_MINUTES // ONE_TIMESTEP
ONE_HOUR_FREQ = "1H"

ONE_DAY_TIMESTEPS = 288  # ONE_DAY_MINUTES // ONE_TIMESTEP
ONE_DAY_FREQ = "1D"

ONE_WEEK_TIMESTEPS = 2016  # ONE_DAY_TIMESTEPS * 7
ONE_WEEK_FREQ = "1W"
